export const PARAMS_TYPES = {
    SET_DEPENDIENTE: 'SET_DEPENDIENTE',
    SET_INDEPENDIENTE: 'SET_INDEPENDIENTE',
    SET_TIME: 'SET_TIME',
    ADD_COLUMNS: 'ADD_COLUMNS',
    ADD_PREDICTS: 'ADD_PREDICTS',
    CLEAR_PARAMS: 'CLEAR_PARAMS'
}